on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          binary_name: smtp-relay
          asset_name: ${BINARY_NAME}-${GOOS}-${GOARCH}
          compress_assets: OFF